
services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '2gb'
    command: >
      bash -c "
        cd /workspace && 
        jupyter notebook
      "
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: bind
        source: $HOME/work/dataset
        target: /dataset
    ports:
      - ${ML_PORT}:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  benchmark:
    build:
      context: .
      dockerfile: benchmark/docker/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USER_NAME: ${UNAME}
    shm_size: '2gb'
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  hailo_compiler:
    build:
      context: "./compiler/hailo/docker"
      dockerfile: "Dockerfile"
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USER_NAME: ${UNAME}
    shm_size: '2g'
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: ${HOME}/work/dataset
        target: /dataset
    working_dir: "/workspace"
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  yolox:
    build:
      context: "./external/yolox/docker"
      dockerfile: "Dockerfile"
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USER_NAME: ${UNAME}
    shm_size: '2g'
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: ${HOME}/work/dataset
        target: /dataset
    working_dir: "/workspace"
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  rpi_ai_hat:
    build:
      context: "./edge_ai/rpi_ai_hat/docker"
      dockerfile: "Dockerfile"
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USER_NAME: ${UNAME}
    shm_size: '2g'
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=${PWD}
    privileged: true
    volumes:
      - type: bind
        source: "${PWD}"
        target: "${PWD}"
        read_only: false
      - type: bind
        source: ${HOME}/work/dataset
        target: /dataset
        read_only: false
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
        read_only: false
      - type: bind
        source: "/run/udev"
        target: "/run/udev"
        read_only: true
    working_dir: "${PWD}"

