version: '3.9'

services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '2gb'
    command: >
      bash -c "
        cd /workspace && 
        jupyter notebook
      "
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/workspace
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - ${port}:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
