PyTorch_SSDLite320_MobileNetv3_Large_COCO2014:
  name: "PyTorch_SSDLite320_MobileNetv3_Large_COCO2014"
  dataset: "coco2014"
  dataset_dir: "dataset"
  output_dir: "outputs/PyTorch_SSDLite320_MobileNetv3_Large_COCO2014"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""

PyTorch_SSDLite320_MobileNetv3_Large_COCO2017:
  name: "PyTorch_SSDLite320_MobileNetv3_Large_COCO2017"
  dataset: "coco2017"
  dataset_dir: "dataset"
  output_dir: "outputs/PyTorch_SSDLite320_MobileNetv3_Large_COCO2017"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""
