PyTorch_SimpleCNN_CIFAR10:
  name: "PyTorch_SimpleCNN_CIFAR10"
  framework: "PyTorch"
  dataset: "cifar10"
  dataset_dir: "dataset"
  output_dir: "outputs/PyTorch_SimpleCNN_CIFAR10"
  task: "image_classification"
  model_name: "simple_cnn"
  model_path: "../notebooks/001_ImageClassification-CIFAR10-SimpleCNN-PyTorch/model/model.pth"

PyTorch_SSDLite320_MobileNetv3_Large_COCO2014:
  name: "PyTorch_SSDLite320_MobileNetv3_Large_COCO2014"
  framework: "PyTorch"
  dataset: "coco2014"
  dataset_dir: "dataset"
  output_dir: "outputs/PyTorch_SSDLite320_MobileNetv3_Large_COCO2014"
  task: "object_detection"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""

PyTorch_SSDLite320_MobileNetv3_Large_COCO2017:
  name: "PyTorch_SSDLite320_MobileNetv3_Large_COCO2017"
  framework: "PyTorch"
  dataset: "coco2017"
  dataset_dir: "dataset"
  output_dir: "outputs/PyTorch_SSDLite320_MobileNetv3_Large_COCO2017"
  task: "object_detection"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""

ONNX_SSDLite320_MobileNetv3_Large_COCO2014:
  name: "ONNX_SSDLite320_MobileNetv3_Large_COCO2014"
  framework: "ONNX"
  dataset: "coco2014"
  dataset_dir: "dataset"
  output_dir: "outputs/ONNX_SSDLite320_MobileNetv3_Large_COCO2014"
  task: "object_detection"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""

ONNX_SSDLite320_MobileNetv3_Large_COCO2017:
  name: "ONNX_SSDLite320_MobileNetv3_Large_COCO2017"
  framework: "ONNX"
  dataset: "coco2017"
  dataset_dir: "dataset"
  output_dir: "outputs/ONNX_SSDLite320_MobileNetv3_Large_COCO2017"
  task: "object_detection"
  model_name: "ssdlite320_mobilenet_v3_large"
  model_path: ""
